pipeline {
    agent any
        parameters{
            string(name:'SPEC',defaultValue:"cypress/integration/**/**",description:"Enter the script path that you want to execute")
            choice(name:'BROWSER',choice:['chrome','edge','firefox'],description:"Choise the browser where you want to execute your scripts")

        }
        options{
            ansiColor('exterm')
        }
        stages{
            stage('Building'){
                echo "Building the app"
            }
            stage("Testing"){
                steps{
                    bat "npn i"
                    bat "npx cypress run --browser ${Browser} --spec ${SPEC}" 
                }
            }
            stage("Deploying"){
            echo "Deploy the application"
            }
        }
        post{
            always{
               publishHTML (target : [allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'reports',
                    reportFiles: 'index.html',
                    eportName: 'My Reports',
                    reportTitles: 'The Report'])
            }
        }
    }
